export const API_RESOURCES = {
  // GET
  getBaseConfig: 'configbase/getConfigBase',
  getCentersAuthorizationText: 'configbase/getTextAthorizationBase',
  getCustomerParams: 'config/getCustomersParams',
  getRequestByIdDocument: 'BOT/getRequestByIdDocumentForCustomer?',
  getConfigByLang: 'config/getConfigByLang?',
  getInfoCustomer: 'customers/v2/getInfoCustomer',
  getActiveCredits: 'customers/v2/getactivecreditscustomer',
  getHistoryCredits: 'customers/v2/getCreditsHistoryCustomer',
  getDetailCredit: 'customers/v2/getDetailCreditCustomer',
  getCustomerByIdDocumentAndTypeDocument: 'customers/v2/getCustomerByIdDocumentAndTypeDocument',
  getDetailCalculateCreditCustomer: 'customers/v2/getDetailCalculateCreditCustomer',
  getCities: 'locations/GetCities',
  getNeighborhoods: 'locations/GetNeighborhood?locationName=',
  getResendQuestion: 'BOT/resendQuestion?',
  getForgotRecoveryPassword: 'account/forgotPassword',
  getCloseSesion: 'customer/closeSession',
  getStatusCertificate: 'customers/v2/getCustomerAccountStatus?',
  getUrlBasePaymentPlan: 'https://paymentplan.z20.web.core.windows.net/',
  getPaymentStatus: 'paymentgateway/ValidatePaymentZonaVirtualStatus?',
  getActiveCreditsQuickPayment: 'paymentgateway/GetPaymentsPagosTerceros?',
  getAuthorizationToken: 'BOT/getAuthorizationToken',
  getInfoPayment: 'paymentgateway/GetInfoPaymentZonaVirtual?',
  getUniqueEmailValidation: 'account/uniqueEmailValidation',
  getValidateUniqueMobileNumber: 'customers/v2/getValidateUniqueMobileNumber',
  getCustomerInfo: 'BOT/getCustomer?',
  // POST
  postAutorizationCenters: 'account/authorizeCenters',
  postRegisterUser: 'account/register',
  postLoginUser: 'account/login',
  postValidEmail: 'account/validateEmailDomain',
  postVerifyEmail: 'account/verifyEmail',
  postValidDocumentByEmail : 'customers/v2/validateAssociatedDocumentByEmail',
  postChangePassword: 'account/changePassword',
  postSendToken: 'customers/v2/sendToken',
  postupdateDataCustomer: 'customers/v2/updateDataCustomer',
  postValidateToken: 'customers/v2/validateToken',
  postSavePhotoChat: 'BOT/savePhotoChat',
  postRecoveryPassword: 'account/changePassword',
  postPaymentProcess: 'paymentgateway/PaymentZonaVirtualProcess',
  postCreditReciept: 'payment/getpaymenttemplates',
  // PATCH
  patchChangeEmail: 'BOT/changeEmail',
  patchChangeMobileNumber: 'BOT/changeMobileNumber'

};
